services:
  doco-cd:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:latest
    restart: unless-stopped
    ports:
      - "8080:80"     # Webhook endpoint
      - "9120:9120"   # Prometheus metrics
    environment:
      TZ: Europe/Berlin
      # GitHub access token - see README.md for setup instructions
      # Replace with your actual token or use Docker secrets
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      # Enable polling configuration
      POLL_CONFIG: |
        - url: https://github.com/phonkd/pong-files.git
          reference: main
          interval: 180  # Poll every 3 minutes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data-doco-cd:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/v1/health"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
